In [18]:
# Importamos las librerías necesarias

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_clientes = pd.read_csv("customer-loyalty-history.csv") #abrimos el csv 

display(df_clientes.head(2)) #mostramos los primeros 2  datos

print("=" * 100)

display(df_clientes.tail(2)) # los ultimos 2 datos

print("=" * 100)

display(df_clientes.sample(2)) # aleatoriamente 2 datos

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1689,887464,Canada,Ontario,Sudbury,M5V 1G5,Male,Bachelor,57150.0,Single,Aurora,6369.26,Standard,2014,2,NaN,NaN
15232,767672,Canada,New Brunswick,Fredericton,E3B 2H2,Male,Bachelor,59766.0,Married,Star,8704.28,Standard,2012,10,NaN,NaN

In [3]:
print(f"El dataframe clientes tiene {df_clientes.shape[0]} filas y {df_clientes.shape[1]} columnas")

El dataframe clientes tiene 16737 filas y 16 columnas

In [4]:
df_info_vuelos = pd.read_csv("customer-flight-activity.csv")

display(df_info_vuelos.head(2))

print("=" * 100)

display(df_info_vuelos.tail(2))

print("=" * 100)

display(df_info_vuelos.sample(2))

,loyalty number,year,month,flights booked,flights with companions,total flights,distance,points accumulated,points redeemed,dollar cost points redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

====================================================================================================

,loyalty number,year,month,flights booked,flights with companions,total flights,distance,points accumulated,points redeemed,dollar cost points redeemed
403758,999982,2018,12,0,0,0,0,0.0,0,0
403759,999986,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

,loyalty number,year,month,flights booked,flights with companions,total flights,distance,points accumulated,points redeemed,dollar cost points redeemed
327239,511302,2018,8,18,4,22,1914,191.0,0,0
21065,330131,2017,2,7,2,9,1683,168.0,0,0

In [5]:
print(f"El dataframe vuelos tiene {df_info_vuelos.shape[0]} filas y {df_info_vuelos.shape[1]} columnas")

El dataframe vuelos tiene 403760 filas y 10 columnas

In [6]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

In [7]:
df_info_vuelos.info()

<class 'pandas.DataFrame'>
RangeIndex: 403760 entries, 0 to 403759
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loyalty number               403760 non-null  int64
 1   year                         403760 non-null  int64
 2   month                        403760 non-null  int64
 3   flights booked               403760 non-null  int64
 4   flights with companions      403760 non-null  int64
 5   total flights                403760 non-null  int64
 6   distance                     403760 non-null  int64
 7   points accumulated           403760 non-null  float64
 8   points redeemed              403760 non-null  int64
 9   dollar cost points redeemed  403760 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.8 MB

In [8]:
df_clientes.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='str')

In [9]:
# HOMOGENEIZAR NOMBRE COLUMNAS

col_nuevas_clientes = {col: col.lower() for col in df_clientes.columns}

col_nuevas_clientes

{'Loyalty Number': 'loyalty number',
 'Country': 'country',
 'Province': 'province',
 'City': 'city',
 'Postal Code': 'postal code',
 'Gender': 'gender',
 'Education': 'education',
 'Salary': 'salary',
 'Marital Status': 'marital status',
 'Loyalty Card': 'loyalty card',
 'CLV': 'clv',
 'Enrollment Type': 'enrollment type',
 'Enrollment Year': 'enrollment year',
 'Enrollment Month': 'enrollment month',
 'Cancellation Year': 'cancellation year',
 'Cancellation Month': 'cancellation month'}

In [49]:
col_nuevas_vuelos = {col: col.title() for col in df_info_vuelos.columns}

col_nuevas_vuelos

{'loyalty number': 'Loyalty Number',
 'year': 'Year',
 'month': 'Month',
 'flights booked': 'Flights Booked',
 'flights with companions': 'Flights With Companions',
 'total flights': 'Total Flights',
 'distance': 'Distance',
 'points accumulated': 'Points Accumulated',
 'points redeemed': 'Points Redeemed',
 'dollar cost points redeemed': 'Dollar Cost Points Redeemed'}

In [50]:
df_info_vuelos.rename(columns=col_nuevas_vuelos, inplace=True)
df_info_vuelos.head(2)

,Loyalty Number,Year,Month,Flights Booked,Flights With Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

## ANALISIS DESCRIPTIVO

In [13]:
# clientes numericas

df_clientes.describe(include="number").T

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,16737.0,549735.880445,258912.132453,100018.00,326603.00,550434.00,772019.00,999986.00
Salary,12499.0,79245.609409,35008.297285,-58486.00,59246.50,73455.00,88517.50,407228.00
CLV,16737.0,7988.896536,6860.982280,1898.01,3980.84,5780.18,8940.58,83325.38
Enrollment Year,16737.0,2015.253211,1.979111,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,16737.0,6.669116,3.398958,1.00,4.00,7.00,10.00,12.00
Cancellation Year,2067.0,2016.503145,1.380743,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,2067.0,6.962748,3.455297,1.00,4.00,7.00,10.00,12.00

In [14]:
# clientes categoricas
 

df_clientes.describe(include="str").T

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

In [15]:
#vuelos numericas

df_info_vuelos.describe(include="number").T

,count,mean,std,min,25%,50%,75%,max
loyalty number,403760.0,549875.383713,258961.514684,100018.0,326699.0,550598.0,772152.0,999986.0
year,403760.0,2017.500352,0.500000,2017.0,2017.0,2018.0,2018.0,2018.0
month,403760.0,6.501335,3.451982,1.0,4.0,7.0,10.0,12.0
flights booked,403760.0,4.134050,5.230064,0.0,0.0,1.0,8.0,21.0
flights with companions,403760.0,1.036569,2.080472,0.0,0.0,0.0,1.0,11.0
total flights,403760.0,5.170619,6.526858,0.0,0.0,1.0,10.0,32.0
distance,403760.0,1214.460979,1434.098521,0.0,0.0,525.0,2342.0,6293.0
points accumulated,403760.0,124.263761,146.696179,0.0,0.0,53.0,240.0,676.5
points redeemed,403760.0,30.838587,125.758002,0.0,0.0,0.0,0.0,876.0
dollar cost points redeemed,403760.0,2.495973,10.172033,0.0,0.0,0.0,0.0,71.0

In [16]:
df_info_vuelos.columns

Index(['loyalty number', 'year', 'month', 'flights booked',
       'flights with companions', 'total flights', 'distance',
       'points accumulated', 'points redeemed', 'dollar cost points redeemed'],
      dtype='str')

In [60]:
col_categoricas_clientes = df_clientes.select_dtypes(include = "str").columns

col_categoricas_clientes

for col in col_categoricas_clientes:
    print(f"ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA {col}")
    print(df_clientes[col].unique())
    print("=" * 100)

ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Country
<StringArray>
['Canada']
Length: 1, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Province
<StringArray>
[             'Ontario',              'Alberta',     'British Columbia',
               'Quebec',                'Yukon',        'New Brunswick',
             'Manitoba',          'Nova Scotia',         'Saskatchewan',
         'Newfoundland', 'Prince Edward Island']
Length: 11, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA City
<StringArray>
[       'Toronto',       'Edmonton',      'Vancouver',           'Hull',
     'Whitehorse',        'Trenton',       'Montreal',   'Dawson Creek',
    'Quebec City',    'Fredericton',         'Ottawa',      'Tremblant',
        'Calgary',    'Thunder Bay',       'Whistler',    'Peace River',
       'Winnipeg',        'Sudbury', 'West Vancouver',        'Halifax',
         'London',         'Regina',        'Kelowna',     'St. John's',
       'Victoria',       'Kingston',          'Banff',        'Moncton',
  'Charlottetown']
Length: 29, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Postal Code
<StringArray>
['M2Z 4K1', 'T3G 6Y6', 'V6E 3D9', 'P1W 1K4', 'J8Y 3Z5', 'Y2K 6R0', 'P5S 6R4',
 'K8V 4B2', 'H2Y 2W2', 'M8Y 4K8', 'U5I 4F1', 'G1B 3L5', 'H4G 3T4', 'M2M 7K8',
 'M2M 6J7', 'E3B 2H2', 'M1R 4K3', 'T9G 1W3', 'H2Y 4R4', 'V5R 1W3', 'P1L 8X8',
 'K1F 2R2', 'H5Y 2S9', 'V1E 4R6', 'H2T 2J6', 'T3E 2V9', 'H2T 9K8', 'K8T 5M5',
 'V6T 1Y8', 'P2T 6G3', 'T9O 2W2', 'V6E 3Z3', 'R6Y 4T5', 'M5V 1G5', 'V6V 8Z3',
 'B3J 9S2', 'M5B 3E4', 'R2C 0M5', 'S6J 3G0', 'M2P 4F6', 'P1J 8T7', 'V09 2E9',
 'A1C 6H9', 'V10 6T5', 'B3C 2M8', 'M9K 2P4', 'T4V 1D4', 'R3R 3T4', 'S1J 3C5',
 'E1A 2A7', 'K1G 4Z0', 'H3T 8L4', 'C1A 6E8', 'H3J 5I6', 'M3R 4K8']
Length: 55, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Education
<StringArray>
['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']
Length: 5, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Marital Status
<StringArray>
['Married', 'Divorced', 'Single']
Length: 3, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Loyalty Card
<StringArray>
['Star', 'Aurora', 'Nova']
Length: 3, dtype: str
====================================================================================================
ESTAMOS ANALIZANDO CATEGORIAS DE LA COLUMNA Enrollment Type
<StringArray>
['Standard', '2018 Promotion']
Length: 2, dtype: str
====================================================================================================

In [61]:
df_clientes["City"] = df_clientes["City"].str.replace(".", "", regex=False).str.replace("'", "", regex=False)

df_clientes["City"].unique() #quito el punto de la ciudad de st john

<StringArray>
[       'Toronto',       'Edmonton',      'Vancouver',           'Hull',
     'Whitehorse',        'Trenton',       'Montreal',   'Dawson Creek',
    'Quebec City',    'Fredericton',         'Ottawa',      'Tremblant',
        'Calgary',    'Thunder Bay',       'Whistler',    'Peace River',
       'Winnipeg',        'Sudbury', 'West Vancouver',        'Halifax',
         'London',         'Regina',        'Kelowna',       'St Johns',
       'Victoria',       'Kingston',          'Banff',        'Moncton',
  'Charlottetown']
Length: 29, dtype: str

In [62]:
df_clientes.head(2)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

In [17]:
df_clientes["Salary"].agg(["min", "max"])#para ver el salario minimo y el maximo

min    -58486.0
max    407228.0
Name: Salary, dtype: float64

In [ ]:
df_clientes.loc[df_clientes["Salary"] < 0, "Salary"] = np.nan #convertir los datos negativos en nan

## DUPLICADOS

In [20]:
print(df_clientes.duplicated().sum()) #para ver numero de duplicados
print(df_info_vuelos.duplicated().sum())

0
0

In [21]:
df_info_vuelos.columns

Index(['loyalty number', 'year', 'month', 'flights booked',
       'flights with companions', 'total flights', 'distance',
       'points accumulated', 'points redeemed', 'dollar cost points redeemed'],
      dtype='str')

In [22]:
mascara_duplicados_vuelos = df_info_vuelos.duplicated(keep=False) #muestra original y copia

df_info_vuelos[mascara_duplicados_vuelos].sort_values(by="loyalty number") #ordena los duplicados por el loyalty number

Empty DataFrame
Columns: [loyalty number, year, month, flights booked, flights with companions, total flights, distance, points accumulated, points redeemed, dollar cost points redeemed]
Index: []

In [23]:
df_info_vuelos.drop_duplicates(inplace=True) #borramos duplicados

In [24]:
print(df_info_vuelos.duplicated().sum())

0

## NULOS

In [25]:
print(df_clientes.isnull().sum()) #visualizamos los nulos

print("-" * 100)

print(df_clientes.select_dtypes(include="number").isnull().sum()) # en numericas

print("-" * 100)

print(df_clientes.select_dtypes(include="str").isnull().sum()) # en categoricas


print("-" * 100)

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4258
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64
----------------------------------------------------------------------------------------------------
Loyalty Number            0
Salary                 4258
CLV                       0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64
----------------------------------------------------------------------------------------------------
Country            0
Province           0
City               0
Postal Code        0
Gender             0
Education          0
Marital Status     0
Loyalty Card       0
Enrollment Type    0
dtype: int64
----------------------------------------------------------------------------------------------------

In [26]:
print(df_info_vuelos.isnull().sum())

print("-" * 100)

print(df_info_vuelos.select_dtypes(include="number").isnull().sum())

print("-" * 100)

loyalty number                 0
year                           0
month                          0
flights booked                 0
flights with companions        0
total flights                  0
distance                       0
points accumulated             0
points redeemed                0
dollar cost points redeemed    0
dtype: int64
----------------------------------------------------------------------------------------------------
loyalty number                 0
year                           0
month                          0
flights booked                 0
flights with companions        0
total flights                  0
distance                       0
points accumulated             0
points redeemed                0
dollar cost points redeemed    0
dtype: int64
----------------------------------------------------------------------------------------------------

In [27]:
nulos_clientes =(df_clientes.select_dtypes(include="number").isnull().sum() / df_clientes.shape[0]) * 100

df_nulos_clientes = nulos_clientes.reset_index() #calculamos el porcentaje de nulos

In [28]:
df_nulos_clientes  #cambiamos nombre de las columnas de dataframe 

df_nulos_clientes.rename(columns={"index" : "nombre_columna", 0 : "% nulos"}, inplace=True)

df_nulos_clientes

       nombre_columna    % nulos
0      Loyalty Number   0.000000
1              Salary  25.440640
2                 CLV   0.000000
3     Enrollment Year   0.000000
4    Enrollment Month   0.000000
5   Cancellation Year  87.650117
6  Cancellation Month  87.650117

In [29]:
mascara_nulos_clientes = df_nulos_clientes["% nulos"] > 0 #filtramos todas las columnas que tengan nulos

df_nulos_clientes = df_nulos_clientes[mascara_nulos_clientes]
df_nulos_clientes

       nombre_columna    % nulos
1              Salary  25.440640
5   Cancellation Year  87.650117
6  Cancellation Month  87.650117

In [30]:
# Para imputación de nulos usando métodos estadísticos avanzados
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Necesario para IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer 



#. Configuración de Pandas para visualizar todas las columnas
pd.set_option('display.max_columns', None)

In [31]:
#como tengo muchos nulos lo hago por tecnicas avanzadas
lista_imputacion_avanzada = ["Salary","Cancellation Year","Cancellation Month"]

In [32]:
# 1. Definimos el imputer
knn_imputer = KNNImputer(n_neighbors=5)

# 2. Elegimos las columnas de origen
columnas_originales = ["Salary", "Cancellation Year", "Cancellation Month"]

# 3. Definimos los nombres de las nuevas
columnas_nuevas = ["Salary knn", "Cancellation Year knn", "Cancellation Month knn"]

# 4. Ejecutamos y ASIGNAMOS 
df_clientes[columnas_nuevas] = knn_imputer.fit_transform(df_clientes[columnas_originales])

# 5. Verificamos
df_clientes.head(2)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Salary knn,Cancellation Year knn,Cancellation Month knn
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,83236.000000,2016.000000,8.400000
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN,79429.572642,2016.503145,6.962748

In [33]:
#definimos el imputer

iterative_imputer = IterativeImputer(random_state=42, max_iter=20) 

#elegimos columnas de origen
columnas_originales = ["Salary", "Cancellation Year", "Cancellation Month"]

# 3. Definimos los nombres de las nuevas
columnas_nuevas_iter =["Salary iter","Cancellation Year iter", "Cancellation Month iter"]

# 4. Ejecutamos y ASIGNAMOS 
df_clientes[columnas_nuevas_iter] =iterative_imputer.fit_transform(df_clientes[columnas_originales])

# 5. Verificamos
df_clientes.head(2)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Salary knn,Cancellation Year knn,Cancellation Month knn,Salary iter,Cancellation Year iter,Cancellation Month iter
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,83236.000000,2016.000000,8.400000,83236.000000,2016.502560,6.959932
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN,79429.572642,2016.503145,6.962748,79429.572643,2016.503138,6.962716

In [34]:
df_clientes[["Salary","Salary knn","Salary iter","Cancellation Year","Cancellation Year knn","Cancellation Year iter","Cancellation Month","Cancellation Month knn","Cancellation Month iter"]].agg(["mean","median"]).T
# Miramos a ver cuanto altera al original

                                 mean        median
Salary                   79429.572642  73510.000000
Salary knn               79411.675807  79429.572642
Salary iter              79429.572643  79429.572643
Cancellation Year         2016.503145   2017.000000
Cancellation Year knn     2016.475463   2016.503145
Cancellation Year iter    2016.503138   2016.503138
Cancellation Month           6.962748      7.000000
Cancellation Month knn       6.964790      6.962748
Cancellation Month iter      6.962716      6.962716

In [35]:
df_clientes.drop(columns=["Salary","Salary knn","Cancellation Year","Cancellation Year knn","Cancellation Month","Cancellation Month knn"],inplace=True)

In [36]:
df_clientes.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Marital Status', 'Loyalty Card', 'CLV',
       'Enrollment Type', 'Enrollment Year', 'Enrollment Month', 'Salary iter',
       'Cancellation Year iter', 'Cancellation Month iter'],
      dtype='str')

In [37]:
df_clientes.rename(columns={"Salary iter" : "Salary" , "Cancellation Year iter" : "Cancellation Year" , "Cancellation Month iter" : "Cancellation Month"},inplace=True)

In [38]:
cols_enteras = ["Cancellation Year", "Cancellation Month"]

# 1. Redondeamos para que 2016.2 sea 2016.0
# 2. Convertimos a Int64 (el que permite nulos y es más robusto)
df_clientes[cols_enteras] = df_clientes[cols_enteras].round(0).astype("Int64")

# Verificamos el resultado
df_clientes.head(2)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Salary,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.000000,2017,7
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,Divorced,Star,3839.61,Standard,2016,3,79429.572643,2017,7

In [39]:
df_clientes.dtypes

Loyalty Number          int64
Country                   str
Province                  str
City                      str
Postal Code               str
Gender                    str
Education                 str
Marital Status            str
Loyalty Card              str
CLV                   float64
Enrollment Type           str
Enrollment Year         int64
Enrollment Month        int64
Salary                float64
Cancellation Year       Int64
Cancellation Month      Int64
dtype: object

In [40]:
df_clientes["Salary"].describe()

count     16737.000000
mean      79429.572643
std       29986.165418
min       15609.000000
25%       63991.000000
50%       79429.572643
75%       82940.000000
max      407228.000000
Name: Salary, dtype: float64

In [41]:
df_clientes["Cancellation Year"].describe()

count        16737.0
mean     2016.859294
std         0.570425
min           2013.0
25%           2017.0
50%           2017.0
75%           2017.0
max           2018.0
Name: Cancellation Year, dtype: Float64

In [42]:
df_clientes["Cancellation Month"].describe()

count     16737.0
mean     6.995399
std      1.214079
min           1.0
25%           7.0
50%           7.0
75%           7.0
max          12.0
Name: Cancellation Month, dtype: Float64

In [43]:
df_clientes.isnull().sum()

Loyalty Number        0
Country               0
Province              0
City                  0
Postal Code           0
Gender                0
Education             0
Marital Status        0
Loyalty Card          0
CLV                   0
Enrollment Type       0
Enrollment Year       0
Enrollment Month      0
Salary                0
Cancellation Year     0
Cancellation Month    0
dtype: int64

In [44]:
#guardamos csv sin nulos
df_clientes.to_csv("clientes_limpio.csv", index=False)

In [51]:

df_info_vuelos.to_csv("vuelos_limpio.csv", index=False)

In [52]:
# Unificamos por la columna 'Loyalty Number'
df_final = pd.merge(df_clientes, df_info_vuelos, on="Loyalty Number", how="inner")

# Verificamos el resultado
print(f"Filas totales después de la unión: {df_final.shape[0]}")
df_final.head()

Filas totales después de la unión: 403760

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Salary,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights With Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.0,2017,7,2017,1,0,0,0,0,0.0,0,0
1,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.0,2017,7,2017,2,3,0,3,2823,282.0,0,0
2,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.0,2017,7,2017,3,0,0,0,0,0.0,0,0
3,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.0,2017,7,2017,4,0,0,0,0,0.0,0,0
4,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,Married,Star,3839.14,Standard,2016,2,83236.0,2017,7,2018,10,6,2,8,3352,335.0,465,38

In [53]:
df_final.to_csv("info_unida.csv", index=False)